### ISSUE TITLE
support string with single quotes

### ISSUE THREAD

**Issue by i9** [thesofakillers/vscode-pbtxt#3]
in pbtxt, single quotes can also enclose string, see comments at https://github.com/protocolbuffers/protobuf-go/blob/v1.25.0/internal/encoding/text/decode_string.go#L29

it's particularly useful for string that has double quotes in it. eg. `field: '{"key": "value"}'` field value is a string of valid json
I tried to edit the regex in pbtxt.tmLanguage.json but couldn't get it work.

Thanks for the helpful extension!

**Comment by i9** [comment]
maybe it should be `\"([^\"]*)\"|'([^']*)'`
or use begin/end for string?

**Comment by thesofakillers** [comment]
@i9 Deployed fix above to VSCode Marketplace. 
Let me know if you have any more issues. 
Thanks!

**Comment by i9** [comment]
awesome. really appreciated!
