### ISSUE TITLE
👋 from textproto-grammar

### ISSUE THREAD

**Issue by thejustinwalsh** [thesofakillers/vscode-pbtxt#4]
I got really excited and created this without even knowing that vscode-pbtxt was a thing.

https://github.com/thejustinwalsh/textproto-grammar

Feel free to grab anything and add to yours if you find it useful. Notably the fenced code block support that was contributed.

Anyhow, two can exist, and who knows you are I may diverge wildly at some point with whatever our project needs, but wanted to reach out! Great minds think alike!

**Comment by thesofakillers** [comment]
Hi, looks awesome! I no longer use VSCode so I doubt I'll be maintaining this repo, which is a port anyway. Does your implementation cover everything mine does? If so, I'll probably archive this repo and redirect users to yours. What do you think?

**Comment by thejustinwalsh** [comment]
Oh dang! The universe just out there working things out. Haha.

Your repo has some tests, and that PR for single quotes, let me pull in tests and verify that fix and I'll give you the good word here in a few.

**Comment by thejustinwalsh** [comment]
This refactor should fix nesting and single quote strings. Sitting on it as it is late, and will work up a release after some more testing.
https://github.com/thejustinwalsh/textproto-grammar/pull/6

**Comment by thejustinwalsh** [comment]
Updated to support single quotes and correctly highlights your test file.
https://github.com/thejustinwalsh/textproto-grammar/releases/tag/v0.0.6

Published on the market place as well.

**Comment by thesofakillers** [comment]
Awesome, just give me a thumbs up whenever and i'll archive this repo and add a note to the readme redirecting to yours 👍🏻

**Comment by thejustinwalsh** [comment]
@thesofakillers one final change to the highlight and keywords, v0.0.7 heading to the marketplace.
textproto-grammar now supports and renders like vscode-pbtxt and adds support for herodoc and markdown code fences.

Good to go!

**Comment by thesofakillers** [comment]
note added to readme in bffc90d. Also published updated readme to marketplace. Archiving after this comment.
